version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashier_be_redis
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: cashier_be_redis
    ports:
      - "6379:6379"
